[workspace]
members = [
  "junction",
  "volt_add",
  "volt_cache",
  "volt_cli",
  "volt_clone",
  "volt_compress",
  "volt_core",
  "volt_create",
  "volt_deploy",
  "volt_help",
  "volt_init",
  "volt_install",
  "volt_utils",
  "volt_list",
  "volt_migrate",
  "volt_remove",
  "volt_run",
  "volt_unknown",
]
