[package]
name = "volt"
version = "0.1.0"
authors = ["XtremeDevX <xtremedevx@gmail.com>", "Ari Seyhun <ariseyhun@live.com.au> (https://ariseyhun.com)"]
description = "A fast, memory-safe package manager for the web."
edition = "2018"

[dependencies]
async-trait = "0.1.50"
colored = "2.0.0"
console  = "0.14.1"
dialoguer = "0.8.0"
dirs = "1.0.5"
futures-util = "0.3.14"
indicatif = "0.16.0"
minreq = "2.3.1"
reqwest = { version = "0.11.3", features = ["stream", "blocking"] }
sha1 = "0.6.0"
rusqlite = "0.25.3"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
tokio = { version = "1.5.0", features = ["full"] }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
