[workspace]
members = [
  "junction",
  "volt_add",
  "volt_cache",
  "volt_cli",
  "volt_clone",
  "volt_compress",
  "volt_core",
  "volt_create",
  "volt_deploy",
  "volt_help",
  "volt_init",
  "volt_install",
  "volt_utils",
  "volt_list",
  "volt_migrate",
  "volt_remove",
  "volt_run",
  "volt_scripts",
  "volt_fix",
  "volt_watch",
  "volt_upgrade",
  "volt_set",
  "volt_audit",
  "volt_check",
  "volt_info",
  "volt_search",
  "volt_outdated",
  "volt_login",
  "volt_logout",
  "volt_publish",
  "volt_tag",
  "volt_owner",
  "volt_team",
  "rslint_parser",
  "rslint_errors",
  "rslint_lexer",
  "rslint_rowan",
  "rslint_syntax",
  "rslint_core",
  "rslint_macros",
  "rslint_lsp",
  "rslint_regex",
  "rslint_text_edit",
  "rslint_config",
  "rslint_cli"
]


[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
